FROM your_mirror_url

WORKDIR /your_root_path

COPY . .

RUN pip install -r requirements.txt

ENV APP_ENV=prod
ENV LOG_PATH=your_log_path
ENV PYTHONPATH=/your_root_path
ENV PROCESS_PORT=8849

CMD ["python", "-m", "app.xxl_job.scheduler_server"]
